In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [2]:
# Load dataset
file = 'C:/Users/mahes/OneDrive/Desktop/FinalYearProjects/Projects/ASD-Detection-App/app/data/dataset-asd.csv'
data = pd.read_csv(file)

In [3]:
# Drop the 'Case_No' column (not useful for training)
data = data.drop(columns=['Case_No'])

In [4]:
# print out multiple patients at the same time
data.loc[:10]

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score,Sex,Ethnicity,Jaundice,Family_mem_with_ASD,Who completed the test,Class/ASD Traits
0,0,0,0,0,0,0,1,1,0,1,28,3,f,middle eastern,yes,no,family member,No
1,1,1,0,0,0,1,1,0,0,0,36,4,m,White European,yes,no,family member,Yes
2,1,0,0,0,0,0,1,1,0,1,36,4,m,middle eastern,yes,no,family member,Yes
3,1,1,1,1,1,1,1,1,1,1,24,10,m,Hispanic,no,no,family member,Yes
4,1,1,0,1,1,1,1,1,1,1,20,9,f,White European,no,yes,family member,Yes
5,1,1,0,0,1,1,1,1,1,1,21,8,m,black,no,no,family member,Yes
6,1,0,0,1,1,1,0,0,1,0,33,5,m,asian,yes,no,family member,Yes
7,0,1,0,0,1,0,1,1,1,1,33,6,m,asian,yes,no,family member,Yes
8,0,0,0,0,0,0,1,0,0,1,36,2,m,asian,no,no,family member,No
9,1,1,1,0,1,1,0,1,1,1,22,8,m,south asian,no,no,Health Care Professional,Yes
10,1,0,0,1,0,1,1,0,1,1,36,6,m,Hispanic,yes,yes,family member,Yes

In [5]:
# print out a description of the dataframe
data.describe()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score
count,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000
mean,0.565877,0.451185,0.402844,0.514692,0.524171,0.580095,0.649289,0.458768,0.490995,0.587678,27.977251,5.225592
std,0.501583,0.503532,0.492632,0.505681,0.499652,0.505174,0.477419,0.498533,0.502049,0.494409,8.741244,2.936764
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,3.000000
50%,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,30.000000,5.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.000000,8.000000
max,3.000000,3.000000,2.000000,3.000000,1.000000,4.000000,1.000000,1.000000,2.000000,2.000000,144.000000,19.000000

In [6]:
# Encode categorical features
categorical_cols = ['Sex', 'Ethnicity', 'Jaundice', 'Family_mem_with_ASD', 'Who completed the test']
data = pd.get_dummies(data, columns=categorical_cols)

In [7]:
data.loc[:10]

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,Ethnicity_south asian,Jaundice_no,Jaundice_yes,Family_mem_with_ASD_no,Family_mem_with_ASD_yes,Who completed the test_Health Care Professional,Who completed the test_Health care professional,Who completed the test_Others,Who completed the test_Self,Who completed the test_family member
0,0,0,0,0,0,0,1,1,0,1,...,False,False,True,True,False,False,False,False,False,True
1,1,1,0,0,0,1,1,0,0,0,...,False,False,True,True,False,False,False,False,False,True
2,1,0,0,0,0,0,1,1,0,1,...,False,False,True,True,False,False,False,False,False,True
3,1,1,1,1,1,1,1,1,1,1,...,False,True,False,True,False,False,False,False,False,True
4,1,1,0,1,1,1,1,1,1,1,...,False,True,False,False,True,False,False,False,False,True
5,1,1,0,0,1,1,1,1,1,1,...,False,True,False,True,False,False,False,False,False,True
6,1,0,0,1,1,1,0,0,1,0,...,False,False,True,True,False,False,False,False,False,True
7,0,1,0,0,1,0,1,1,1,1,...,False,False,True,True,False,False,False,False,False,True
8,0,0,0,0,0,0,1,0,0,1,...,False,True,False,True,False,False,False,False,False,True
9,1,1,1,0,1,1,0,1,1,1,...,True,True,False,True,False,True,False,False,False,False
10,1,0,0,1,0,1,1,0,1,1,...,False,False,True,False,True,False,False,False,False,True

In [8]:
# Encode target variable ('Class/ASD Traits ') → Convert 'Yes' to 1 and 'No' to 0
data['Class/ASD Traits '] = data['Class/ASD Traits '].map({'Yes': 1, 'No': 0})

In [10]:
# Define feature (X) and target (Y) variables
X = data.drop(columns=['Class/ASD Traits '])  # All features except target
Y = data['Class/ASD Traits ']

In [11]:
# print the new categorical column labels
X.columns.values

array(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10',
       'Age_Mons', 'Qchat-10-Score', 'Sex_f', 'Sex_m',
       'Ethnicity_Hispanic', 'Ethnicity_Latino',
       'Ethnicity_Native Indian', 'Ethnicity_Others',
       'Ethnicity_Pacifica', 'Ethnicity_White European',
       'Ethnicity_asian', 'Ethnicity_black', 'Ethnicity_middle eastern',
       'Ethnicity_mixed', 'Ethnicity_south asian', 'Jaundice_no',
       'Jaundice_yes', 'Family_mem_with_ASD_no',
       'Family_mem_with_ASD_yes',
       'Who completed the test_Health Care Professional',
       'Who completed the test_Health care professional',
       'Who completed the test_Others', 'Who completed the test_Self',
       'Who completed the test_family member'], dtype=object)

In [12]:
# print an example patient from the categorical data
X.loc[1]

A1                                                     1
A2                                                     1
A3                                                     0
A4                                                     0
A5                                                     0
A6                                                     1
A7                                                     1
A8                                                     0
A9                                                     0
A10                                                    0
Age_Mons                                              36
Qchat-10-Score                                         4
Sex_f                                              False
Sex_m                                               True
Ethnicity_Hispanic                                 False
Ethnicity_Latino                                   False
Ethnicity_Native Indian                            False
Ethnicity_Others                                   False
Ethnicity_Pacifica                                 False
Ethnicity_White European                            True
Ethnicity_asian                                    False
Ethnicity_black                                    False
Ethnicity_middle eastern                           False
Ethnicity_mixed                                    False
Ethnicity_south asian                              False
Jaundice_no                                        False
Jaundice_yes                                        True
Family_mem_with_ASD_no                              True
Family_mem_with_ASD_yes                            False
Who completed the test_Health Care Professional    False
Who completed the test_Health care professional    False
Who completed the test_Others                      False
Who completed the test_Self                        False
Who completed the test_family member                True
Name: 1, dtype: object

In [13]:
Y.iloc[:10]

0    0
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    0
9    1
Name: Class/ASD Traits , dtype: int64

In [15]:
# Train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [16]:
# Convert to NumPy arrays
X_train = np.array(X_train, dtype=np.float32)
X_test = np.array(X_test, dtype=np.float32)
Y_train = np.array(Y_train, dtype=np.float32)
Y_test = np.array(Y_test, dtype=np.float32)

### Building the Network - Keras

In [17]:
# Define the neural network model
def create_model():
    model = Sequential()
    model.add(Dense(16, input_dim=X_train.shape[1], activation='relu'))  # Adjusted input size
    model.add(Dense(8, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))  # Binary classification (output 1 neuron)
    
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])
    return model

### Training the Network

Now it's time for the fun! Training a Keras model is as simple as calling model.fit().

In [18]:
# Create and train the model
model = create_model()
print(model.summary())

# Train the model
model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=1)

c:\Users\mahes\OneDrive\Desktop\FinalYearProjects\Projects\ASD-Detection-App\venv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 705 (2.75 KB)

 Trainable params: 705 (2.75 KB)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6513 - loss: 0.6510
Epoch 2/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6748 - loss: 0.5224
Epoch 3/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3462
Epoch 4/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9419 - loss: 0.2223
Epoch 5/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9529 - loss: 0.1686
Epoch 6/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9580 - loss: 0.1416
Epoch 7/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9664 - loss: 0.1194
Epoch 8/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9575 - loss: 0.1090
Epoch 9/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9775 - loss: 0.0907
Epoch 10/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9725 - loss: 0.0866
Epoch 11/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9849 - loss: 0.0676
Epoch 12/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9818 - loss: 0.0702
Epoch 13/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9896 - loss: 0.0483
Epoch 14/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9869 - loss: 0.0546
Epoch 15/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9922 - loss: 0.0507
Epoch 16/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0419
Epoch 17/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9943 - loss: 0.0376
Epoch 18/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9943 - loss: 0.0400
Epoch 19/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9926 - loss: 0.0373
Epoch 20/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9853 - loss: 0.0436
Epoch 21/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9954 - loss: 0.0287
Epoch 22/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9952 - loss: 0.0315
Epoch 23/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9932 - loss: 0.0310
Epoch 24/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9968 - loss: 0.0241
Epoch 25/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0240
Epoch 26/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9992 - loss: 0.0234
Epoch 27/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9975 - loss: 0.0294
Epoch 28/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9973 - loss: 0.0219
Epoch 29/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9980 - loss: 0.0172
Epoch 30/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0157
Epoch 31/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9982 - loss: 0.0191
Epoch 32/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0138
Epoch 33/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0122
Epoch 34/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0129
Epoch 35/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0118
Epoch 36/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0116
Epoch 37/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0114
Epoch 38/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0083
Epoch 39/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0089
Epoch 40/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0115
Epoch 41/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0070
Epoch 42/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0075
Epoch 43/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0074
Epoch 44/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0074
Epoch 45/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0046
Epoch 46/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0062
Epoch 47/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 48/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0042
Epoch 49/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0050
Epoch 50/50
85/85 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.0039

In [20]:
# Make predictions
predictions = (model.predict(X_test) > 0.5).astype(int)  # Convert probabilities to binary (0/1)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [21]:
# Print results
print('Results for Binary Classification Model:')
print('Accuracy:', accuracy_score(Y_test, predictions))
print(classification_report(Y_test, predictions))

Results for Binary Classification Model:
Accuracy: 1.0
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        67
         1.0       1.00      1.00      1.00       144

    accuracy                           1.00       211
   macro avg       1.00      1.00      1.00       211
weighted avg       1.00      1.00      1.00       211